#!/bin/bash
# Vercel Environment Setup Script
# This script updates Vercel environment variables for both frontend and backend

echo "🔗 BETNEXA Vercel Deployment Configuration"
echo "==========================================="
echo ""

echo "✓ Frontend URL: https://betnexa.vercel.app"
echo "✓ Backend URL: https://betnexa-globalback.vercel.app"
echo ""

echo "Step 1: Link Frontend Project"
echo "-----------------------------"
echo "Run this command:"
echo "  npx vercel link --project betnexa"
echo ""

echo "Step 2: Link Backend Project"  
echo "----------------------------"
echo "Run this command:"
echo "  cd server"
echo "  npx vercel link --project server-chi-orcin"
echo ""

echo "Step 3: Pull Environment Variables"
echo "----------------------------------"
echo "Frontend environment:"
echo "  npx vercel env pull .env.local"
echo ""
echo "Backend environment:"
echo "  cd server"
echo "  npx vercel env pull .env"
echo ""

echo "Step 4: Set Environment Variables on Vercel"
echo "-------------------------------------------"
echo ""
echo "FRONTEND (https://vercel.com/dashboard/betnexa/settings/environment-variables)"
echo "Add or update these variables:"
echo "  VITE_SUPABASE_URL=https://eaqogmybihiqzivuwyav.supabase.co"
echo "  VITE_SUPABASE_ANON_KEY=<your-supabase-anon-key>"
echo "  VITE_API_URL=https://betnexa-globalback.vercel.app"
echo ""
echo "BACKEND (https://vercel.com/dashboard/server-chi-orcin/settings/environment-variables)"
echo "Add or update these variables:"
echo "  SUPABASE_URL=https://eaqogmybihiqzivuwyav.supabase.co"
echo "  SUPABASE_SERVICE_KEY=<your-supabase-service-key>"
echo "  SUPABASE_ANON_KEY=<your-supabase-anon-key>"
echo "  PAYHERO_API_KEY=<your-payhero-api-key>"
echo "  PAYHERO_API_SECRET=<your-payhero-api-secret>"
echo "  PAYHERO_ACCOUNT_ID=3398"
echo "  NODE_ENV=production"
echo ""

echo "Step 5: Redeploy Both Projects"
echo "------------------------------"
echo "After adding environment variables:"
echo "1. Go to Frontend Deployments → Click latest → Redeploy"
echo "2. Go to Backend Deployments → Click latest → Redeploy"
echo ""

echo "✅ Once environment variables are set and redeployed:"
echo "   - Frontend: https://betnexa.vercel.app"
echo "   - Backend: https://betnexa-globalback.vercel.app/api/health"
